remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: notGPT User Guide
description: A user guide for notGPT 
show_downloads: true

github:
  zip_url: https://github.com/flyingsalsa/ip/releases/download/v0.2/notGPT.jar
